# Generated by Django 3.1.4 on 2021-01-08 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ebook.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Janr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janr', models.CharField(max_length=50)),
                ('janr_img', models.ImageField(blank=True, upload_to=ebook.models.janr_img_name)),
            ],
            options={
                'ordering': ['janr'],
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('user_img', models.ImageField(blank=True, upload_to=ebook.models.reader_img_name)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=50)),
                ('title', models.TextField()),
                ('book_img', models.ImageField(blank=True, upload_to=ebook.models.book_img_name)),
                ('bookfile', models.FileField(blank=True, upload_to=ebook.models.book_file_name)),
                ('aftor', models.CharField(max_length=200)),
                ('cost', models.FloatField(max_length=10)),
                ('user_id', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('janr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebook.janr')),
            ],
        ),
    ]
